export const CREDIT_TRANSACTION = "CREDIT_TRANSACTION";
export const DEBIT_TRANSACTION = "DEBIT_TRANSACTION";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const ADD_CATEGORY = "ADD_CATEGORY";
